version: '2'
services:
  tango-db:
    container_name: tango-mysql
    image: tangocs/mysql:9.2.2
    environment:
     - MYSQL_ROOT_PASSWORD=root
  tango-cs:
    container_name: tango-cs
    image: tangocs/tango-cs:9
    ports:
     - "10000:10000"
    environment:
     - TANGO_HOST=localhost:10000
     - MYSQL_HOST=tango-db:3306
     - MYSQL_USER=tango
     - MYSQL_PASSWORD=tango
     - MYSQL_DATABASE=tango
    depends_on:
     - tango-db